<template>
  <component :is="iconComponent" :size="size" :weight="weight" v-if="iconComponent" />
</template>

<script setup>
import { computed } from 'vue'
import {
  PhX, PhCheck, PhPencilSimple, PhTrash, PhPaperPlaneRight,
  PhMagnifyingGlass, PhArrowCounterClockwise, PhArrowUUpLeft,
  PhArrowLeft, PhCaretRight, PhCaretLeft, PhCaretDown, PhCaretUp,
  PhCaretCircleRight, PhDotsSixVertical, PhList, PhCheckSquare,
  PhCheckCircle, PhLightbulb, PhBugDroid, PhLinkSimple, PhFileText,
  PhFile, PhNotePencil, PhMapPinSimple, PhCalendarDot, PhCalendarBlank,
  PhBellRinging, PhPanorama, PhAperture, PhVideo, PhEqualizer,
  PhMapPinArea, PhMapTrifold, PhChartBar, PhTrendUp,
  PhChartBarHorizontal, PhChartDonut, PhListBullets, PhListNumbers,
  PhQuotes, PhGridNine, PhFilePlus, PhTerminal, PhGear, PhCommand,
  PhPaintBrushBroad, PhExport, PhUsers, PhBuilding, PhSignOut,
  PhFileJs, PhFileArrowDown, PhFileCsv, PhFileHtml, PhFolder,
  PhHouseSimple, PhSuitcase, PhBooks, PhGameController, PhRocketLaunch,
  PhPlanet, PhHeartbeat, PhUser, PhSparkle, PhMicroscope, PhBarricade,
  PhGraduationCap, PhLightning, PhChats, PhArchive, PhInfo,
  PhWarningOctagon, PhStar, PhListStar, PhFrameCorners,
  PhArrowsClockwise, PhPencilLine, PhArrowUDownRight
} from '@phosphor-icons/vue'

const props = defineProps({
  name: { type: String, required: true },
  size: { type: [Number, String], default: 18 },
  weight: { type: String, default: 'regular' }
})

const ICON_MAP = {
  'x': PhX,
  'check': PhCheck,
  'pencil-simple': PhPencilSimple,
  'trash': PhTrash,
  'paper-plane-right': PhPaperPlaneRight,
  'magnifying-glass': PhMagnifyingGlass,
  'arrow-counter-clockwise': PhArrowCounterClockwise,
  'arrow-u-up-left': PhArrowUUpLeft,
  'arrow-u-down-right': PhArrowUDownRight,
  'arrow-left': PhArrowLeft,
  'caret-right': PhCaretRight,
  'caret-left': PhCaretLeft,
  'caret-down': PhCaretDown,
  'caret-up': PhCaretUp,
  'caret-circle-right': PhCaretCircleRight,
  'dots-six-vertical': PhDotsSixVertical,
  'list': PhList,
  'check-square': PhCheckSquare,
  'check-circle': PhCheckCircle,
  'lightbulb': PhLightbulb,
  'bug-droid': PhBugDroid,
  'link-simple': PhLinkSimple,
  'file-text': PhFileText,
  'file': PhFile,
  'note-pencil': PhNotePencil,
  'map-pin-simple': PhMapPinSimple,
  'calendar-dot': PhCalendarDot,
  'calendar-blank': PhCalendarBlank,
  'bell-ringing': PhBellRinging,
  'panorama': PhPanorama,
  'aperture': PhAperture,
  'video': PhVideo,
  'equalizer': PhEqualizer,
  'map-pin-area': PhMapPinArea,
  'map-trifold': PhMapTrifold,
  'chart-bar': PhChartBar,
  'trend-up': PhTrendUp,
  'chart-bar-horizontal': PhChartBarHorizontal,
  'chart-donut': PhChartDonut,
  'list-bullets': PhListBullets,
  'list-numbers': PhListNumbers,
  'quotes': PhQuotes,
  'grid-nine': PhGridNine,
  'file-plus': PhFilePlus,
  'terminal': PhTerminal,
  'gear': PhGear,
  'command': PhCommand,
  'paint-brush-broad': PhPaintBrushBroad,
  'export': PhExport,
  'users': PhUsers,
  'building': PhBuilding,
  'sign-out': PhSignOut,
  'file-js': PhFileJs,
  'file-arrow-down': PhFileArrowDown,
  'file-csv': PhFileCsv,
  'file-html': PhFileHtml,
  'folder': PhFolder,
  'house-simple': PhHouseSimple,
  'suitcase': PhSuitcase,
  'books': PhBooks,
  'game-controller': PhGameController,
  'rocket-launch': PhRocketLaunch,
  'planet': PhPlanet,
  'heartbeat': PhHeartbeat,
  'user': PhUser,
  'sparkle': PhSparkle,
  'microscope': PhMicroscope,
  'barricade': PhBarricade,
  'graduation-cap': PhGraduationCap,
  'lightning': PhLightning,
  'chats': PhChats,
  'archive': PhArchive,
  'info': PhInfo,
  'warning-octagon': PhWarningOctagon,
  'star': PhStar,
  'list-star': PhListStar,
  'frame-corners': PhFrameCorners,
  'arrows-clockwise': PhArrowsClockwise,
  'pencil-line': PhPencilLine,
}

const iconComponent = computed(() => ICON_MAP[props.name] || null)
</script>
